#ifndef TOKENKIND_H_
#define TOKENKIND_H_

typedef enum TokenKind {
    TOKENKIND_LEFT_BRACE,
    TOKENKIND_RIGHT_BRACE,
    TOKENKIND_LEFT_PAREN,
    TOKENKIND_RIGHT_PAREN,
    TOKENKIND_LEFT_BRACKET,
    TOKENKIND_RIGHT_BRACKET,
} TokenKind;

#endif